name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/spotsure-devops-assignment

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old containers..."
            docker compose down

            echo "Building new containers..."
            docker compose up -d --build

            echo "Removing unused images..."
            docker image prune -f

            echo "Running containers:"
            docker ps
          EOF
